spring:
  datasource:
    url: ${STORAGE_DB_URL:jdbc:mysql://localhost:3306/patra_storage?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC}
    username: ${STORAGE_DB_USERNAME:root}
    password: ${STORAGE_DB_PASSWORD:root}

logging:
  file:
    path: ${PAPERTRACE_LOG_DIR:./logs}/patra-storage
  level:
    com.patra.storage: INFO
