spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${INGEST_DB_URL}
    username: ${INGEST_DB_USERNAME}
    password: ${INGEST_DB_PASSWORD}
  data:
    redis:
      url: ${INGEST_REDIS_URL}

patra:
  starter:
    expr:
      mode:
        strict: true
        multi:
          repeat-enabled: false
      compiler:
        enabled: true
        query-param-bridge:
          enabled: true
        max-query-length: 5000
        warn-param-count: 50
        max-param-count: 100
