spring:
  datasource:
    url: ${STORAGE_DB_URL:jdbc:postgresql://localhost:15432/patra_storage}
    username: ${STORAGE_DB_USERNAME:postgres}
    password: ${STORAGE_DB_PASSWORD:123456}

logging:
  file:
    path: ${PATRA_LOG_DIR:./logs}/patra-object-storage
  level:
    dev.linqibin.patra.objectstorage: INFO
