spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/patra_registry?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      url: redis://localhost:16379
