package com.patra.starter.provenance.common.exception;

import java.util.Objects;

/**
 * Provenance client exception base class.
 *
 * <p>Wraps downstream errors occurring while calling provenance data sources directly via HTTP.
 * Additional metadata (HTTP status, trace/correlation id when available, response body) is captured
 * to assist troubleshooting.
 *
 * @author linqibin
 * @since 0.1.0
 */
public class ProvenanceClientException extends RuntimeException {

  private final String provenanceCode;
  private final String apiName;
  private final Integer statusCode;
  private final String traceId;
  private final String responseBody;

  /**
   * Create an exception with minimal diagnostic information.
   *
   * @param provenanceCode provenance source identifier
   * @param apiName API method name that failed
   * @param message human readable message
   */
  public ProvenanceClientException(String provenanceCode, String apiName, String message) {
    this(provenanceCode, apiName, null, null, null, message, null);
  }

  /**
   * Create an exception with a nested cause and message.
   *
   * @param provenanceCode provenance source identifier
   * @param apiName API method name that failed
   * @param message human readable message
   * @param cause underlying exception
   */
  public ProvenanceClientException(
      String provenanceCode, String apiName, String message, Throwable cause) {
    this(provenanceCode, apiName, null, null, null, message, cause);
  }

  /**
   * Create an exception enriched with HTTP metadata and an optional trace identifier.
   *
   * @param provenanceCode provenance source identifier
   * @param apiName API method name that failed
   * @param statusCode optional downstream HTTP status code
   * @param traceId optional gateway trace identifier
   * @param responseBody optional raw response body for diagnostics
   * @param message human readable message
   * @param cause underlying exception, if any
   */
  public ProvenanceClientException(
      String provenanceCode,
      String apiName,
      Integer statusCode,
      String traceId,
      String responseBody,
      String message,
      Throwable cause) {
    super(formatMessage(provenanceCode, apiName, statusCode, traceId, message), cause);
    this.provenanceCode = Objects.requireNonNull(provenanceCode, "provenanceCode cannot be null");
    this.apiName = Objects.requireNonNull(apiName, "apiName cannot be null");
    this.statusCode = statusCode;
    this.traceId = traceId;
    this.responseBody = responseBody;
  }

  private static String formatMessage(
      String provenanceCode, String apiName, Integer statusCode, String traceId, String message) {
    StringBuilder builder =
        new StringBuilder("[").append(provenanceCode).append("][").append(apiName).append("] ");
    if (statusCode != null) {
      builder.append("status=").append(statusCode).append(' ');
    }
    if (traceId != null) {
      builder.append("traceId=").append(traceId).append(' ');
    }
    builder.append(message);
    return builder.toString();
  }

  /**
   * Get the provenance source identifier.
   *
   * @return provenance code string
   */
  public String getProvenanceCode() {
    return provenanceCode;
  }

  /**
   * Get the API name associated with the failure.
   *
   * @return API name string
   */
  public String getApiName() {
    return apiName;
  }

  /**
   * Get the downstream HTTP status code if provided.
   *
   * @return optional status code
   */
  public Integer getStatusCode() {
    return statusCode;
  }

  /**
   * Get the trace identifier propagated by downstream or generated by caller.
   *
   * @return trace identifier or {@code null}
   */
  public String getTraceId() {
    return traceId;
  }

  /**
   * Get the raw response body captured from the downstream response.
   *
   * @return response payload or {@code null}
   */
  public String getResponseBody() {
    return responseBody;
  }
}
